CREATE TABLE `contract` (
  `id` BIGINT NOT NULL,
  `organ_id` BIGINT NOT NULL COMMENT '租户/机构标识',
  `user_id` BIGINT NOT NULL,
  `dept_path` VARCHAR(128) NOT NULL,
  `contract_no` VARCHAR(128),
  `contract_id` BIGINT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态[ACTIVE:有效, INACTIVE:无效]',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标志：0未删除，1已删除',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` INT NOT NULL DEFAULT 0 COMMENT '记录版本',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户表';